### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/data-blog#5]
Can we please add tracking code for analytics:

UA-42057855-6

Not sure what your preferred method is, but this is the recommended way (in ```<HEAD>```):

```<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-42057855-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-42057855-6');
</script>
```

**Comment by dnoesgaard** [comment]
Btw: https://gohugo.io/templates/internal#google-analytics

**Comment by MattBlissett** [comment]
Depending how things are set up, that probably requires a cookie consent banner.

**Comment by jhnwllr** [comment]
So should I add the script tag to the header? Or do we need a cookie consent banner first?

**Comment by dnoesgaard** [comment]
Hey John, as the blog is getting more attention, we'd like to have Analytics up and running. Can you look into getting a cookie consent banner and adding the tracking code?

**Comment by jhnwllr** [comment]
I will look into it. I am not really sure how to implement a cookie consent banner. I guess it is just some javascript that runs in the background, which then allows Google Analytics to run if pressed?

**Comment by dnoesgaard** [comment]
Something like that. The user has to explicitly accept the use of cookies before any are used.

Perhaps @MortenHofft can provide some advice?

**Comment by MortenHofft** [comment]
Google analytics will run either way. The banner only informs that it happens. As far as I remember there are several drop in js snippets that will do it for you. https://www.gbif.org/terms/privacy-policy
